on:
  issues:
    types: [opened]
   
jobs:
  thank-user:
    runs-on: ubuntu-20.04
    name: Comment module name for the Issue
    outputs:
      module-name: ${{ steps.extract-name.outputs.module-name }}
    steps:
      - name: Extract module name
        id: extract-name
        run: |
          module_name=$(echo "${{ github.event.issue.title }}" | sed -E 's/\[(.*)\].*/\1/')
      - name: comment on the issue
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.MOCHILIA_COMMENT_TOKEN }}
          repository: 'MoChilia/ActionsDemo'
          number: ${{ github.event.issue.number }}
          id: module-name-comment
          message: '${{ steps.extract-name.outputs.module-name }}'
