name: Run an Azure CLI script by inline commands

on:
  workflow_dispatch:
  pull_request_target:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.48.0
        inlineScript: |
          az account show
