name: Run Azure Login with non-OIDC secret

on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
         creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    - name: 'Get web app list'
      run: |
        az webapp list --query "[?state=='Running']"
    - name: 'Log out'
      run: |
        az logout
        az cache purge
        az account clear
        az account show
        pwd 
