name: Run Azure Login with non-OIDC secret

on:
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
    - name: 'Get web app list'
      run: |
        az webapp list --query "[?state=='Running']"
        
    - name: 'Show az account'
      run: |
          az account show
        
    - name: 'Log out'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
