name: Run Azure Login using sp with secret

on:
  workflow_dispatch:
  pull_request:

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Show az account'
      run: |
          az account show
