name: Run Azure Login with OIDC

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  id-token: write
  contents: read

jobs: 

  test:
    runs-on: ubuntu-latest
    environment: azure_authorize_github
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Show az account'
        run: |
          az account show
