name: Run Azure Login with non-OIDC secret

on:
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Show az account'
      run: |
          az account show
