name: Test Azure CLI for escaping in env

on:
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Run Azure CLI
      uses: MoChilia/CLI@escape-by-args
      env:
        TESTENV1: "A message with \"double quotes\""
        TESTENV2: $(whoami)
        TESTENV3: "Single quote '\"'\"' in string"
        TESTENV4: "echo !a"
      with:
        inlineScript: |
          echo $TESTENV1
          echo $TESTENV2
          echo $TESTENV3
          echo $TESTENV4
