name: Set idle label for issues

# Controls when the action will run.
on:
  schedule:
  - cron: "0 0/3 * * *"
  workflow_dispatch:

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/stale@v3
        name: Setting issue as idle
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is idle because it has been open for 1 day with no activity.'
          stale-issue-label: 'idle'
          days-before-stale: 1
          days-before-close: 1
          operations-per-run: 100
          exempt-issue-labels: 'backlog'

      - uses: actions/stale@v3
        name: Setting PR as idle
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is idle because it has been open for 1 day with no activity.'
          stale-pr-label: 'idle'
          days-before-stale: 1
          days-before-close: -1
          operations-per-run: 100