name: Negative Test OIDC for Azure China Cloud

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: MoChilia/login@OIDC-sovereign-cloud-test
        with:
          client-id: ${{ secrets.AZURE_CHINA_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_CHINA_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_CHINA_SUBSCRIPTION_ID }}
          environment: 'AzureChinaCloud'
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd
