name: Test ChangeLog

on:
  workflow_dispatch:

jobs: 
   test: 
      runs-on: ubuntu-latest 
      steps: 
       - name: Checkout source code
         uses: actions/checkout@v3 

       - name: Gen Changelog and Tag sources
         id: changelog
         uses: TriPSs/conventional-changelog-action@latest
         with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
