name: Releases
on:
  workflow_dispatch:
    inputs:
      Version:
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.Version }}
          prerelease: true
          
#       - uses: actions/checkout@v3
# 
#       - name: conventional Changelog Action
#         id: changelog
#         uses: TriPSs/conventional-changelog-action@v3
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN  }}

#       - name: create release
#         uses: actions/create-release@v1
#         if: ${{ steps.changelog.outputs.skipped == 'false' }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
#         with:
#           tag_name: ${{ steps.changelog.outputs.tag }}
#           release_name: ${{ steps.changelog.outputs.tag }}
#           body: ${{ steps.changelog.outputs.clean_changelog }}
