on: [push]
name: Azure System-assigned Managed Identity sample
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Azure Login
      uses: mochilia/login@managed-identity-test-1
      with:
        enable-managed-identity: true
    - run: |
          az account show
