name: UpdateApp

on: 
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/a2ff229a-d488-4f2c-b4fd-a6de4c837780/' --headers 'Content-Type=application/json' --body '{"spa":{"redirectUris":["https://www.getpostman.com/oauth2/callback"]}}'
