name: UpdateApp

on: 
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}
    
    - run: |
        az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/2cd62102-3318-4792-a6dc-defb9f2736ac/' --headers 'Content-Type=application/json' --body '{"spa":{"redirectUris":["https://www.getpostman.com/oauth2/callback"]}}'
